# Generated by Django 3.0.8 on 2021-04-09 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='tweet-media'),
        ),
    ]
