# Generated by Django 3.0.8 on 2021-04-15 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0003_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.AddField(
            model_name='tweet',
            name='is_video',
            field=models.BooleanField(default=False),
        ),
    ]
