# Generated by Django 3.0.8 on 2021-04-15 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0004_auto_20210415_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='thumbnail',
            field=models.FileField(blank=True, null=True, upload_to='thumbnails/audio'),
        ),
    ]
