# Generated by Django 3.0.8 on 2021-04-19 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0007_auto_20210419_0910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='thumbnail',
        ),
    ]
