# Generated by Django 3.2 on 2021-05-13 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='mail_verified',
            field=models.BooleanField(default=False),
        ),
    ]
